variables:
  TAG_ENV: Prod
  TAG_PURPOSE: Deploy
  AWS_ACCESS_KEY_ID: $TF_VAR_aws_access_key_id
  AWS_SECRET_ACCESS_KEY: $TF_VAR_aws_secret_access_key
  SOCKETS_PORT: 5080
  NODE_ENV: production
  NODE_PATH: /srv/app/node_modules

before_script:
  - aws --version
  - echo nodejs $(node --version)
  - echo npm $(npm --version)
  - echo yarn $(yarn --version)
  - echo semgrep $(semgrep --version)

stages:
  - test

lint:
  retry: 2
  tags:
    - python
  stage: test
  script:
    - make lint
  only:
    refs:
      - merge_request
      - main
