before_script:
  - aws --version

stages:
  - build
  - deploy

build:
  retry: 2
  tags:
    - python
  stage: build
  variables:
    COMMON_VERSION: 0.1.4
    NODE_ENV: production
    NODE_PATH: /home/ec2-user/node_modules
  script:
    - make package
  only:
    refs:
      - merge_request

build-upload:
  retry: 2
  tags:
    - python
  stage: build
  variables:
    COMMON_VERSION: 0.1.4
    NODE_ENV: production
    NODE_PATH: /home/ec2-user/node_modules
    AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
    AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
    AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
  script:
    - make package-upload
  only:
    refs:
      - master

deploy:
  tags:
    - python
  stage: deploy
  variables:
    AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
    AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
    AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
    DEFAULT_INSTANCE_TYPE: t2.micro
    SUBNET_ID: subnet-8b05e8c3
    SECURITY_GROUP_IDS: sg-0c1d7baef47bb7c14 sg-01bbdeecc61359d59
    IAM_INSTANCE_PROFILE: EC2-TrivialSec
    COST_CENTER: saas
    PRIV_KEY_NAME: trivialsec-prod
    TARGET_GROUP_ARN: arn:aws:elasticloadbalancing:ap-southeast-2:814504268053:targetgroup/trivialsec-prod-sockets/00073980e0e9f7a8
  script:
    - COUNT=$(aws elbv2 describe-target-health --target-group-arn ${TARGET_GROUP_ARN} --query 'TargetHealthDescriptions[]' | jq '. | length')
    - echo ${COUNT}
    - bash -c "./deploy/launch-sockets.sh ${COUNT}"
  only:
    refs:
      - master
