version: '3.6'
x-defaults: &defaults
  env_file: .env
  # network_mode: host
  restart: unless-stopped
  logging:
    options:
      max-size: "10m"
      max-file: "3"

services:
  push-service:
    <<: *defaults
    image: trivialsec/push-service
    container_name: push-service
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NODE_ENV: development
    environment:
      - SOCKETS_PORT=5080
      - CONFIG_FILE=src/${CONFIG_FILE}
    expose:
      - 5080
    volumes:
      - ./src:/srv/app/src
    cap_drop:
      - ALL
    cap_add:
      - DAC_OVERRIDE
    healthcheck:
      test: curl -f http://ws.trivialsec:5080/healthcheck || exit 1
      timeout: 20s
      retries: 10
    networks:
      default:
        aliases:
          - push-service
          - push

networks:
  default:
    external:
      name: trivialsec
      