version: '3.9'
services:
  push-service:
    image: trivialsec/sockets
    container_name: sockets
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NODE_ENV: ${NODE_ENV}
        NODE_PATH: ${NODE_PATH}
    environment:
      - SOCKETS_PORT=5080
      - CONFIG_FILE=src/${CONFIG_FILE}
    ports:
      - 5080:5080
    expose:
      - 5080
    volumes:
      - ./src:/srv/app/src
    cap_drop:
      - ALL
    cap_add:
      - DAC_OVERRIDE
    healthcheck:
      test: curl -f http://localhost:5080/healthcheck || exit 1
      timeout: 20s
      retries: 10
    networks:
      default:
        aliases:
          - dockets
          - push-service
          - push
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 10
      resources:
        limits:
          cpus: '1.00'
          memory: 1GB
        reservations:
          memory: 500M
    logging:
      options:
        max-size: "10m"
        max-file: "3"

networks:
  default:
    external:
      name: trivialsec
