version: '3.9'
services:
  push-service:
    env_file: .env
    image: trivialsec/push-service
    container_name: push-service
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NODE_ENV: development
    environment:
      - SOCKETS_PORT=5080
      - CONFIG_FILE=src/${CONFIG_FILE}
    expose:
      - 5080
    volumes:
      - ./src:/srv/app/src
    cap_drop:
      - ALL
    cap_add:
      - DAC_OVERRIDE
    healthcheck:
      test: curl -f http://push.trivialsec:5080/healthcheck || exit 1
      timeout: 20s
      retries: 10
    networks:
      default:
        aliases:
          - push-service
          - push
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 0s
        max_attempts: 10
        window: 3s
      resources:
        limits:
          cpus: '1.00'
          memory: 1GB
        reservations:
          cpus: '0.50'
          memory: 500M

networks:
  default:
    external:
      name: trivialsec
      