---
app:
  version: 21.6.28
  default_port: 5080
  proxy:
    host: proxy.trivialsec.local
    port: 3128
  frontend:
    asset_scheme: "https://"
    asset_domain: www.trivialsec.com
    site_scheme: "https://"
    site_domain: www.trivialsec.com
    app_scheme: "https://"
    app_domain: app.trivialsec.com
    api_scheme: "https://"
    api_domain: api.trivialsec.com
    socket_scheme: "http://"
    socket_domain: localhost:5080
  backend:
    socket_scheme: "http://"
    socket_domain: push-service:5080
