---
app:
  version: 21.3.1
  default_port: 5080
  log_file: /tmp/application.log
  frontend:
    site_scheme: "http://"
    site_domain: localhost:5000
    socket_scheme: "http://"
    socket_domain: localhost:5080
  backend:
    socket_scheme: "http://"
    socket_domain: sockets:5080
