---
app:
  version: 21.3.20
  default_port: 5080
  log_file: /tmp/application.log
  proxy:
    host: proxy.trivialsec.local
    port: 3128
  frontend:
    site_scheme: "http://"
    site_domain: www.trivialsec.com
    app_scheme: "https://"
    app_domain: app.trivialsec.com
    api_scheme: "https://"
    api_domain: api.trivialsec.com
    socket_scheme: "http://"
    socket_domain: localhost:5080
  backend:
    socket_scheme: "http://"
    socket_domain: sockets:5080
